"""Knowledge package providing style example retrieval, index caching, and validation."""

from .migration import (
    KnowledgeDualWriteManager,
    KnowledgeParityChecker,
    MigrationStage,
    ParityVerificationReport,
)
from .models import (
    Base,
    KnowledgeAlias,
    KnowledgeEvidence,
    KnowledgeRecord,
    PortableVector,
    VectorType,
)
from .repository import KnowledgeRepository
from .retrieval import (
    EmbeddingService,
    HybridKnowledgeRetriever,
    cosine_similarity,
    find_similar_knowledge_records,
)
from .style_retrieval import (
    CANONICAL_INTENT_TAXONOMY,
    CRITICAL_UNRENDERED_TOKENS,
    DATASET_FILE,
    SMSExampleIndex,
    STRICT_PLACEHOLDER_ALLOWLIST,
    STYLE_EXAMPLES_ENABLED,
    STYLE_STOP_WORDS,
    STYLE_TEMPLATE_FALLBACKS,
    TEMPLATE_VARIABLE_PATTERN,
    TOKEN_RE,
    UNRESOLVED_PLACEHOLDER_PATTERNS,
    classify_query_intent,
    example_index,
    get_example_index,
    get_style_examples,
    is_style_examples_enabled,
    render_style_examples,
    render_template_variables,
    resolve_dataset_path,
    set_example_index,
    set_style_examples_enabled,
    tokenise,
    validate_no_unresolved_placeholders,
)

__all__ = [
    "Base",
    "KnowledgeRecord",
    "KnowledgeEvidence",
    "KnowledgeAlias",
    "KnowledgeRepository",
    "MigrationStage",
    "ParityVerificationReport",
    "KnowledgeParityChecker",
    "KnowledgeDualWriteManager",
    "PortableVector",
    "VectorType",
    "EmbeddingService",
    "HybridKnowledgeRetriever",
    "cosine_similarity",
    "find_similar_knowledge_records",
    "CANONICAL_INTENT_TAXONOMY",
    "CRITICAL_UNRENDERED_TOKENS",
    "DATASET_FILE",
    "SMSExampleIndex",
    "STRICT_PLACEHOLDER_ALLOWLIST",
    "STYLE_EXAMPLES_ENABLED",
    "STYLE_STOP_WORDS",
    "STYLE_TEMPLATE_FALLBACKS",
    "TEMPLATE_VARIABLE_PATTERN",
    "TOKEN_RE",
    "UNRESOLVED_PLACEHOLDER_PATTERNS",
    "classify_query_intent",
    "example_index",
    "get_example_index",
    "get_style_examples",
    "is_style_examples_enabled",
    "render_style_examples",
    "render_template_variables",
    "resolve_dataset_path",
    "set_example_index",
    "set_style_examples_enabled",
    "tokenise",
    "validate_no_unresolved_placeholders",
]

